name: Scheduled API Tests

on:
  push:
    branches:
      - dev

jobs:
  run-api-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - uses: matt-ball/newman-action@master
      with:
        collection: api-tests.json
        reporters: json
        
    

    - name: Transfer test results via SCP
      run: sshpass -p "${{ secrets.SSH_PASSWORD }}" scp result.json ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/boilerplate-be

    
