name: Laravel CI DEV

on:
  push:
    branches:
      - dev
      
jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: pgsql, pdo_pgsql, zip, bcmath

      - name: Set up PostgreSQL
        uses: minesunny/postgresql-action@v1.0.0
        with:
          postgresql_version: '11'

      - name: Install PHP dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Set environment variables for CI
        run: |
          cp .env.example .env
          echo "APP_KEY=${{ secrets.APP_KEY }}" >> .env
          echo "DB_CONNECTION=pgsql" >> .env
          echo "DB_HOST=localhost" >> .env
          echo "DB_PORT=5432" >> .env
          echo "DB_DATABASE=testdb" >> .env
          echo "DB_USERNAME=postgres" >> .env
          echo "DB_PASSWORD=postgres" >> .env

      - name: Ensure database is ready
        run: |
          psql -U postgres -d testdb -c "SELECT 1"

      - name: Run database migrations
        run: php artisan migrate --force

      - name: Clear configuration cache
        run: php artisan config:clear

      - name: Run Laravel tests
        run: php artisan test

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "About to Deploy"
            cd /var/www/langlearnai-be/deployment
            eval $(ssh-agent)
            ssh-add ~/.ssh/id_ecdsa
            git pull origin dev
            composer install
            php artisan migrate --force
