name: Code Quality

on:
  pull_request:
    branches:
      - dev
      
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: zip, bcmath

      - name: Install PHP dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Run PHP Linting
        run: |
          find . -type f -name "*.php" | xargs -n1 php -l
